[build]
  command = "yarn build"
  functions = "out_functions"
  publish   = "out_publish"
[[plugins]]
  package = "@netlify/plugin-nextjs"

# preview
[context.deploy-preview]
  command = "yarn build"
  publish   = "deploy-preview_out_publish"
  functions = "deploy-preview_out_functions"
